#!/usr/bin/env python3
"""Are the scores probabilities, and do they mean what they say?

A prevalence study does two things with a detector score: it compares it against a
threshold, and it sometimes reads the score itself as a confidence. The first needs the
score to rank; the second needs it to be calibrated, meaning that among artifacts scored
0.8, about 80 per cent should be agent-written.

Only two of the seven instruments produce a number that could be a probability. The LLM
judge is asked for one directly, and the supervised classifier emits one. Binoculars,
Fast-DetectGPT and DetectCodeGPT return unbounded statistics -- a negated perplexity
ratio, a standardised curvature, a rank ratio -- so there is no calibration to measure,
and that is itself the finding: a study reading those numbers as confidences is reading
something the instrument never claimed to provide. The formatting rules return a
fraction of rules matched and the keyword scan a binary flag; neither is a probability
either.

Expected calibration error is computed over ten equal-width bins on the balanced
comparison of agent text against matched pre-ChatGPT text. The base rate there is close
to one half by construction, which is not the rate in any repository, so read the number
as a property of the scores rather than as a deployment estimate.

Usage:
    python calibration.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from metrics import ROOT, load  # noqa: E402

OUT = ROOT / "data" / "processed" / "validity"
TEX = ROOT / "paper" / "generated" / "t_calibration.tex"

# Instruments whose score is meant to be read as a probability.
PROBABILISTIC = {"llm_judge": "LLM judge", "fingerprint": "Supervised ceiling"}
GENRES = [
    ("commit_message", "Commit msg"),
    ("pr_body", "PR body"),
    ("issue_body", "Issue"),
    ("comment", "Comment"),
    ("diff", "Diff"),
]
BINS = 10


def ece(scores: np.ndarray, labels: np.ndarray, bins: int = BINS) -> tuple[float, float]:
    """Expected calibration error, and the mean signed gap between score and outcome.

    The signed gap says which way the miscalibration runs: positive means the instrument
    claims more confidence in the agent class than the outcomes support.
    """
    edges = np.linspace(0.0, 1.0, bins + 1)
    total, signed = 0.0, 0.0
    for i in range(bins):
        lo, hi = edges[i], edges[i + 1]
        in_bin = (scores > lo) & (scores <= hi) if i else (scores >= lo) & (scores <= hi)
        if not in_bin.any():
            continue
        weight = in_bin.mean()
        confidence = scores[in_bin].mean()
        accuracy = labels[in_bin].mean()
        total += weight * abs(confidence - accuracy)
        signed += weight * (confidence - accuracy)
    return total, signed


def main() -> int:
    print("loading scores:")
    df = load()

    rows = []
    for detector in PROBABILISTIC:
        sub_all = df[df.detector == detector]
        for genre, _ in GENRES:
            sub = sub_all[
                (sub_all.genre == genre)
                & ((sub_all.set == "P") | ((sub_all.set == "N1") & (sub_all.matched == True)))  # noqa: E712
            ]
            sub = sub[sub.score.notna()]
            if len(sub) < 200:
                continue
            scores = sub.score.to_numpy(float)
            labels = (sub.set == "P").to_numpy(int)
            value, signed = ece(scores, labels)
            rows.append(
                {
                    "detector": detector,
                    "genre": genre,
                    "n": len(sub),
                    "base_rate": float(labels.mean()),
                    "ece": value,
                    "signed_gap": signed,
                }
            )

    out = pd.DataFrame(rows)
    OUT.mkdir(parents=True, exist_ok=True)
    out.to_parquet(OUT / "rq1_calibration.parquet", index=False)

    print("\nexpected calibration error, balanced comparison\n")
    show = out.copy()
    for col in ("ece", "signed_gap", "base_rate"):
        show[col] = show[col].round(3)
    print(show.to_string(index=False))

    body = []
    for detector, label in PROBABILISTIC.items():
        sub = out[out.detector == detector]
        if sub.empty:
            continue
        cells = []
        for genre, _ in GENRES:
            cell = sub[sub.genre == genre]
            cells.append("---" if cell.empty else f"{cell.ece.iloc[0]:.3f}")
        body.append(f"{label} & " + " & ".join(cells) + r" \\")
    header = ["Instrument"] + [lbl for _, lbl in GENRES]

    TEX.parent.mkdir(parents=True, exist_ok=True)
    TEX.write_text(rf"""% generated by analysis/03_validity/calibration.py -- do not edit
\begin{{table}}[t]
\caption{{Expected calibration error for the two instruments that return a probability.
Zero would mean a score of 0.8 is right eight times in ten.}}
\label{{tab:calibration}}
\small
\begin{{tabular}}{{@{{}}l{"r" * len(GENRES)}@{{}}}}
\toprule
{" & ".join(header)} \\
\midrule
{chr(10).join(body)}
\bottomrule
\end{{tabular}}

\vspace{{2pt}}
{{\footnotesize The other five instruments return unbounded statistics, rule counts or a
binary flag, so they have no calibration to measure.}}
\end{{table}}
""")
    print(f"\nwrote {OUT / 'rq1_calibration.parquet'} and {TEX}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
