#!/usr/bin/env python3
"""Macros for the worked example that runs through the results sections.

The paper needs one artifact a reader can hold on to while the tables accumulate. It has
to be a real row of the corpus, because an invented one would beg the question, and its
numbers have to be generated like every other figure in the manuscript rather than typed
into the text.

The artifact is a pre-ChatGPT commit message, so any detection of it is a false positive
by construction. Repository and author are not recorded here and are not printed in the
paper: the study makes no claim about any individual contributor, and an example that
identified one would break that.

Also emits the inputs of the worked Rogan--Gladen calculation in the correction section,
so the arithmetic printed there cannot drift from the measured sensitivity and
specificity.

Usage:
    python example.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from metrics import CORPUS, ROOT, load  # noqa: E402

TEX = ROOT / "paper" / "generated" / "example_numbers.tex"

# Pinned by text. Chosen because it is flagged by several instruments at once, is short
# enough to quote in full, names no project or person, and reads like what practitioners
# describe as machine-written prose -- which is the point, since it predates the models.
EXAMPLE_TEXT = "fix: improve error handling in WebSockets"
EXAMPLE_GENRE = "commit_message"

# The cell whose arithmetic the correction section walks through.
WORKED_DETECTOR = "binoculars"
WORKED_GENRE = "commit_message"
WORKED_AP = 0.20

LABELS = {
    "binoculars": "Binoculars",
    "fast_detect_gpt": "Fast-DetectGPT",
    "detect_code_gpt": "DetectCodeGPT",
    "heuristics": "the formatting rules",
    "selfadmission": "the keyword scan",
    "llm_judge": "the LLM judge",
    "fingerprint": "the supervised ceiling",
}


def macro(name: str, value: str) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def main() -> int:
    corpus = pd.read_parquet(CORPUS, columns=["source_id", "set", "genre", "text", "n_chars"])
    match = corpus[
        (corpus.text == EXAMPLE_TEXT) & (corpus.genre == EXAMPLE_GENRE) & (corpus.set == "N1")
    ]
    if match.empty:
        raise SystemExit(
            f"example artifact not found in the corpus: {EXAMPLE_TEXT!r}. "
            "It was pinned by text; if the corpus was rebuilt, pick a new one."
        )
    source_id = match.source_id.iloc[0]

    df = load()
    metrics = pd.read_parquet(ROOT / "data" / "processed" / "validity" / "rq1_metrics.parquet")
    thresholds = metrics[metrics.genre == EXAMPLE_GENRE].set_index("detector")

    scored = df[(df.source_id == source_id) & (df.genre == EXAMPLE_GENRE)]
    flagged, total = [], 0
    lines = ["% generated by analysis/03_validity/example.py -- do not edit"]
    for row in scored.itertuples():
        if row.detector not in thresholds.index or not np.isfinite(row.score):
            continue
        total += 1
        threshold = thresholds.loc[row.detector, "threshold"]
        if row.score >= threshold:
            flagged.append(row.detector)
        stem = "".join(part.capitalize() for part in row.detector.split("_"))
        lines += [
            macro(f"Ex{stem}Score", f"{row.score:.3f}"),
            macro(f"Ex{stem}Threshold", f"{threshold:.3f}"),
        ]

    names = [LABELS[d] for d in flagged]
    joined = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
    lines += [
        macro("ExText", EXAMPLE_TEXT),
        macro("ExChars", str(int(match.n_chars.iloc[0]))),
        macro("ExFlagged", str(len(flagged))),
        macro("ExInstruments", str(total)),
        macro("ExFlaggedNames", joined),
    ]

    # Worked correction: the arithmetic the reader is walked through.
    cell = metrics[
        (metrics.detector == WORKED_DETECTOR) & (metrics.genre == WORKED_GENRE)
    ].iloc[0]
    se, sp = cell.recall_at_fpr, 1 - cell.fpr_achieved
    j = se + sp - 1
    numerator = WORKED_AP + sp - 1
    lines += [
        macro("WorkedDetector", LABELS[WORKED_DETECTOR]),
        macro("WorkedAp", f"{100 * WORKED_AP:.0f}"),
        macro("WorkedSe", f"{100 * se:.1f}"),
        macro("WorkedSp", f"{100 * sp:.1f}"),
        macro("WorkedJ", f"{j:+.3f}"),
        macro("WorkedNumerator", f"{numerator:+.3f}"),
        macro("WorkedQuotient", f"{numerator / j:.1f}" if j else "undefined"),
    ]

    TEX.parent.mkdir(parents=True, exist_ok=True)
    TEX.write_text("\n".join(lines) + "\n")

    print(f"example: {EXAMPLE_TEXT!r}")
    print(f"  flagged by {len(flagged)} of {total}: {', '.join(flagged) or 'none'}")
    print(f"  worked cell {WORKED_DETECTOR}/{WORKED_GENRE}: "
          f"Se={100 * se:.1f}%  Sp={100 * sp:.1f}%  J={j:+.3f}")
    print(f"wrote {TEX}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
