#!/usr/bin/env python3
"""Emit the LaTeX tables and inline macros for the results sections.

No number reaches the manuscript by being typed there. Every figure in
Sections~\\ref{sec:validity} and~\\ref{sec:correction} comes from here, so a re-run of
the pipeline moves the paper with it and a stale number cannot survive quietly.

Writes into paper/generated/:
    rq1_validity.tex      AUROC and recall per detector and genre
    rq2_automation.tex    false positives on pre-LLM humans against pre-LLM automation
    rq3_correction.tex    Youden's J and the estimability of the correction
    validity_numbers.tex  macros for figures quoted inline in prose

Usage:
    python tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
VALIDITY = ROOT / "data" / "processed" / "validity"
CORRECTION = ROOT / "data" / "processed" / "correction"
OUT = ROOT / "paper" / "generated"

# Reading order: the three families, then the supervised ceiling. Detectors absent from
# the score files are skipped rather than emitted empty.
ORDER = [
    ("binoculars", "Binoculars"),
    ("fast_detect_gpt", "Fast-DetectGPT"),
    ("detect_code_gpt", "DetectCodeGPT"),
    ("heuristics", "Formatting rules"),
    ("selfadmission", "Self-admission"),
    ("llm_judge", "LLM judge"),
    ("fingerprint", "Supervised (ceiling)"),
]
GENRES = [
    ("commit_message", "Commit msg"),
    ("pr_body", "PR body"),
    ("issue_body", "Issue"),
    ("comment", "Comment"),
    ("diff", "Diff"),
]


def fmt(value: float, digits: int = 3) -> str:
    return "---" if not np.isfinite(value) else f"{value:.{digits}f}"


def pct(value: float, digits: int = 1) -> str:
    return "---" if not np.isfinite(value) else f"{100 * value:.{digits}f}"


def grid(df: pd.DataFrame, column: str, formatter) -> list[str]:
    """One LaTeX row per detector, one column per genre."""
    pivot = df.pivot_table(index="detector", columns="genre", values=column)
    lines = []
    for key, label in ORDER:
        if key not in pivot.index:
            continue
        cells = [formatter(pivot.loc[key].get(g, np.nan)) for g, _ in GENRES]
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    return lines


def rq1_table(metrics: pd.DataFrame) -> str:
    header = " & ".join(label for _, label in GENRES)
    auroc = "\n".join(grid(metrics, "auroc_n1", fmt))
    recall = "\n".join(grid(metrics, "recall_at_fpr", pct))
    return rf"""% generated by analysis/03_validity/tables.py -- do not edit
\begin{{table}}[t]
\caption{{Discrimination against length-matched pre-ChatGPT negatives from the same
repositories. Above: area under the ROC curve, where 0.5 is chance. Below: recall at the
threshold admitting a 5\% false positive rate on those negatives.}}
\label{{tab:rq1}}
\small
\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\toprule
& \multicolumn{{5}}{{c}}{{Artifact genre}} \\
\cmidrule(l){{2-6}}
Instrument & {header} \\
\midrule
\multicolumn{{6}}{{@{{}}l}}{{\emph{{AUROC}}}} \\
{auroc}
\addlinespace
\multicolumn{{6}}{{@{{}}l}}{{\emph{{Recall at 5\% false positive rate (\%)}}}} \\
{recall}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def rq2_table(automation: pd.DataFrame) -> str:
    rows = []
    for key, label in ORDER:
        sub = automation[automation.detector == key]
        if sub.empty:
            continue
        cells = []
        for genre, _ in GENRES:
            cell = sub[sub.genre == genre]
            if cell.empty or not np.isfinite(cell.fpr_bots.iloc[0]):
                cells.append("---")
            else:
                cells.append(f"{100 * cell.fpr_bots.iloc[0]:.1f}")
        rows.append(f"{label} & " + " & ".join(cells) + r" \\")
    header = " & ".join(label for _, label in GENRES)
    body = "\n".join(rows)
    return rf"""% generated by analysis/03_validity/tables.py -- do not edit
\begin{{table}}[t]
\caption{{False positives on pre-ChatGPT automation (\%), at the threshold calibrated to
flag 5\% of pre-ChatGPT human text in the same genre. Both sets predate language models,
so every detection in either is an error; the difference is what the instrument responds
to. Diffs carry no bot stratum.}}
\label{{tab:rq2automation}}
\small
\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\toprule
Instrument & {header} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def rq3_table(correction: pd.DataFrame) -> str:
    rows = []
    for key, label in ORDER:
        sub = correction[correction.detector == key]
        if sub.empty:
            continue
        cells = []
        for genre, _ in GENRES:
            cell = sub[sub.genre == genre]
            if cell.empty:
                cells.append("---")
            else:
                r = cell.iloc[0]
                cells.append(f"{r.youden_j:+.3f}" if np.isfinite(r.youden_j) else "---")
        rows.append(f"{label} & " + " & ".join(cells) + r" \\")
    header = " & ".join(label for _, label in GENRES)
    body = "\n".join(rows)
    return rf"""% generated by analysis/03_validity/tables.py -- do not edit
\begin{{table}}[t]
\caption{{Youden's $J = s + c - 1$, the denominator of the Rogan--Gladen correction, at
the 5\% operating point. The correction divides the observed rate by this quantity, so a
value near zero means the corrected estimate carries no information whatever the
observed rate.}}
\label{{tab:rq3}}
\small
\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\toprule
Instrument & {header} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def macros(metrics: pd.DataFrame, automation: pd.DataFrame,
           correction: pd.DataFrame, length: pd.DataFrame) -> str:
    zero_shot = metrics[metrics.detector.isin(["binoculars", "fast_detect_gpt"])]
    ceiling = metrics[metrics.detector == "fingerprint"]
    judge_gap = automation[automation.detector == "llm_judge"]

    def macro(name: str, value: str) -> str:
        return rf"\newcommand{{\{name}}}{{{value}}}"

    at5 = correction[[c for c in correction.columns if c.startswith("ap05_status")]]
    status = correction["ap05_status"].value_counts() if len(at5) else pd.Series(dtype=int)

    lines = [
        "% generated by analysis/03_validity/tables.py -- do not edit",
        macro("ZeroShotAurocMax", fmt(zero_shot.auroc_n1.max())),
        macro("ZeroShotAurocMin", fmt(zero_shot.auroc_n1.min())),
        macro("ZeroShotBelowChance", str(int((zero_shot.auroc_n1 < 0.5).sum()))),
        macro("ZeroShotCells", str(len(zero_shot))),
        macro("CeilingAurocMax", fmt(ceiling.auroc_n1.max())),
        macro("CeilingAurocMin", fmt(ceiling.auroc_n1.min())),
        macro("CeilingBestGenre", ceiling.loc[ceiling.auroc_n1.idxmax(), "genre"].replace("_", " ")),
        macro("JudgeBotFprMax", pct(judge_gap.fpr_bots.max())),
        macro("JudgeBotFprMin", pct(judge_gap.fpr_bots.min())),
        macro("JudgeBotRatioMin", fmt(judge_gap.ratio.min(), 0)),
        macro("JudgeBotRatioMax", fmt(judge_gap.ratio.max(), 0)),
        macro("SelfAdmissionRecallMax", pct(
            metrics.loc[metrics.detector == "selfadmission", "recall_at_fpr"].max())),
        macro("SelfAdmissionFprMax", pct(
            metrics.loc[metrics.detector == "selfadmission", "fpr_achieved"].max())),
        macro("CorrectionCells", str(len(correction))),
        macro("CorrectionUndefined", str(int(status.get("undefined", 0)))),
        macro("CorrectionOutOfRange", str(int(status.get("out of range", 0)))),
        macro("CorrectionEstimable", str(int(status.get("estimable", 0)))),
    ]

    # The one cell where a correction survives an observed rate of twenty per cent and
    # is worth quoting in prose: the supervised ceiling on pull request bodies.
    ceil_pr = correction[(correction.detector == "fingerprint") & (correction.genre == "pr_body")]
    if len(ceil_pr) and ceil_pr.iloc[0]["ap20_status"] == "estimable":
        r = ceil_pr.iloc[0]
        lines += [
            macro("CeilingCorrectedTwenty", pct(r["ap20_point"])),
            macro("CeilingCorrectedTwentyLo", pct(r["ap20_lo"])),
            macro("CeilingCorrectedTwentyHi", pct(r["ap20_hi"])),
        ]

    # Length trend for the one detector that moves the wrong way, quoted in the prose.
    fdg = length[length.detector == "fast_detect_gpt"]
    if len(fdg):
        low = fdg[fdg.bin == fdg.bin.min()].auroc.mean()
        high = fdg[fdg.bin == fdg.bin.max()].auroc.mean()
        lines += [macro("FastDetectShortAuroc", fmt(low)),
                  macro("FastDetectLongAuroc", fmt(high))]
    ceil_len = length[length.detector == "fingerprint"]
    if len(ceil_len):
        lines += [
            macro("CeilingShortAuroc", fmt(ceil_len[ceil_len.bin == ceil_len.bin.min()].auroc.mean())),
            macro("CeilingLongAuroc", fmt(ceil_len[ceil_len.bin == ceil_len.bin.max()].auroc.mean())),
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    metrics = pd.read_parquet(VALIDITY / "rq1_metrics.parquet")
    automation = pd.read_parquet(VALIDITY / "rq2_automation.parquet")
    length = pd.read_parquet(VALIDITY / "rq2_length.parquet")
    correction = pd.read_parquet(CORRECTION / "rq3_correction.parquet")

    OUT.mkdir(parents=True, exist_ok=True)
    written = {
        "rq1_validity.tex": rq1_table(metrics),
        "rq2_automation.tex": rq2_table(automation),
        "rq3_correction.tex": rq3_table(correction),
        "validity_numbers.tex": macros(metrics, automation, correction, length),
    }
    for name, content in written.items():
        (OUT / name).write_text(content)
        print(f"wrote {OUT / name}")

    missing = sorted({k for k, _ in ORDER} - set(metrics.detector.unique()))
    if missing:
        print(f"\nnot yet scored, omitted from the tables: {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
