#!/usr/bin/env python3
"""Emit the LaTeX tables and inline macros for the results sections.

No number reaches the manuscript by being typed there. Every figure in the results
sections comes from here, so a re-run of the pipeline moves the paper with it and a
stale number cannot survive quietly.

One table answers one question. The results carry three factors at once -- instrument,
genre and error type -- and a grid holding all of them is a data dump the reader has to
mine. Each table below is therefore small enough that a single sentence beside it says
what to take from it.

Writes into paper/generated/:
    t_zeroshot.tex        can the zero-shot detectors separate the classes?
    t_others.tex          can the keyword, rule and judge instruments?
    t_ceiling.tex         is the signal there at all?
    t_recall.tex          what does each instrument recover at a usable threshold?
    t_selfadmission.tex   the precision/recall trade of the keyword scans
    t_automation.tex      do the instruments respond to bots rather than to models?
    t_length.tex          does more text help?
    t_agents.tex          does any of this generalise across agents?
    t_youden.tex          how much information is left for the correction?
    t_estimable.tex       how often the correction is usable at all
    t_corrected.tex       corrected prevalence where it can be computed
    validity_numbers.tex  macros for figures quoted inline in prose

Usage:
    python tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
VALIDITY = ROOT / "data" / "processed" / "validity"
CORRECTION = ROOT / "data" / "processed" / "correction"
OUT = ROOT / "paper" / "generated"

LABELS = {
    "binoculars": "Binoculars",
    "fast_detect_gpt": "Fast-DetectGPT",
    "detect_code_gpt": "DetectCodeGPT",
    "heuristics": "Formatting rules",
    "selfadmission": "Keyword scan",
    "llm_judge": "LLM judge",
    "fingerprint": "Supervised ceiling",
}
ZERO_SHOT = ["binoculars", "fast_detect_gpt", "detect_code_gpt"]
OTHERS = ["selfadmission", "heuristics", "llm_judge"]
CEILING = ["fingerprint"]
ALL = ZERO_SHOT + OTHERS + CEILING

GENRES = [
    ("commit_message", "Commit msg"),
    ("pr_body", "PR body"),
    ("issue_body", "Issue"),
    ("comment", "Comment"),
    ("diff", "Diff"),
]


def fmt(value: float, digits: int = 3) -> str:
    return "---" if not np.isfinite(value) else f"{value:.{digits}f}"


def pct(value: float, digits: int = 1) -> str:
    return "---" if not np.isfinite(value) else f"{100 * value:.{digits}f}"


def table(caption: str, label: str, header: list[str], rows: list[str],
          align: str | None = None, note: str = "") -> str:
    align = align or "l" + "r" * (len(header) - 1)
    body = "\n".join(rows)
    # The blank line is load-bearing: without a paragraph break the note stays in the
    # same horizontal box as the tabular and runs off the right margin.
    tail = f"\n\n\\vspace{{2pt}}\n{{\\footnotesize {note}}}" if note else ""
    return rf"""% generated by analysis/03_validity/tables.py -- do not edit
\begin{{table}}[t]
\caption{{{caption}}}
\label{{{label}}}
\small
\begin{{tabular}}{{@{{}}{align}@{{}}}}
\toprule
{" & ".join(header)} \\
\midrule
{body}
\bottomrule
\end{{tabular}}{tail}
\end{{table}}
"""


def by_genre(metrics: pd.DataFrame, detectors: list[str], column: str, formatter) -> list[str]:
    pivot = metrics.pivot_table(index="detector", columns="genre", values=column)
    rows = []
    for key in detectors:
        if key not in pivot.index:
            continue
        cells = [formatter(pivot.loc[key].get(g, np.nan)) for g, _ in GENRES]
        rows.append(f"{LABELS[key]} & " + " & ".join(cells) + r" \\")
    return rows


def main() -> int:
    metrics = pd.read_parquet(VALIDITY / "rq1_metrics.parquet")
    automation = pd.read_parquet(VALIDITY / "rq2_automation.parquet")
    length = pd.read_parquet(VALIDITY / "rq2_length.parquet")
    agents = pd.read_parquet(VALIDITY / "rq2_agent.parquet")
    correction = pd.read_parquet(CORRECTION / "rq3_correction.parquet")

    genre_header = ["Detector"] + [lbl for _, lbl in GENRES]
    written: dict[str, str] = {}

    # --- RQ1 -------------------------------------------------------------------
    written["t_zeroshot.tex"] = table(
        "Zero-shot detectors: area under the ROC curve against length-matched "
        "pre-ChatGPT text from the same repositories. 0.5 is chance.",
        "tab:zeroshot", genre_header, by_genre(metrics, ZERO_SHOT, "auroc_n1", fmt),
        note="Values below 0.5 mean the detector ranks pre-ChatGPT human text as more "
             "machine-written than agent text.",
    )
    written["t_others.tex"] = table(
        "Keyword scan, formatting rules and LLM judge: area under the ROC curve, "
        "same comparison.",
        "tab:others", genre_header, by_genre(metrics, OTHERS, "auroc_n1", fmt),
    )
    written["t_ceiling.tex"] = table(
        "A classifier trained in domain on the same text, cross-validated in folds "
        "grouped by repository. This is what is available to be found.",
        "tab:ceiling", genre_header, by_genre(metrics, CEILING, "auroc_n1", fmt),
    )
    written["t_recall.tex"] = table(
        "Share of agent-authored artifacts recovered (\\%) at the threshold that flags "
        "5\\% of pre-ChatGPT text in the same genre.",
        "tab:recall", genre_header, by_genre(metrics, ALL, "recall_at_fpr", pct),
    )

    sa = metrics[metrics.detector == "selfadmission"]
    rows = [
        f"{dict(GENRES)[r.genre]} & {pct(r.fpr_achieved)} & {pct(r.recall_at_fpr)} \\\\"
        for r in sa.itertuples() if r.genre in dict(GENRES)
    ]
    written["t_selfadmission.tex"] = table(
        "The keyword scan used by two of the audited studies: false positives against "
        "recall, per genre (\\%).",
        "tab:selfadmission", ["Genre", "False positives", "Recall"], rows,
        align="lrr",
    )

    # --- RQ2 -------------------------------------------------------------------
    rows = []
    for key in ALL:
        sub = automation[automation.detector == key]
        if sub.empty:
            continue
        cells = []
        for genre, _ in GENRES:
            cell = sub[sub.genre == genre]
            cells.append("---" if cell.empty else pct(cell.fpr_bots.iloc[0]))
        rows.append(f"{LABELS[key]} & " + " & ".join(cells) + r" \\")
    written["t_automation.tex"] = table(
        "False positives on pre-ChatGPT bot output (\\%), at the threshold calibrated to "
        "flag 5\\% of pre-ChatGPT human text. Both predate language models, so every "
        "detection in either is an error.",
        "tab:automation", genre_header, rows,
        note="Diffs carry no bot stratum, so that column is empty by design.",
    )

    pivot = length.pivot_table(index="detector", columns="bin", values="auroc")
    rows = [
        f"{LABELS[k]} & " + " & ".join(fmt(pivot.loc[k].get(b, np.nan)) for b in sorted(pivot.columns))
        + r" \\"
        for k in ALL if k in pivot.index
    ]
    written["t_length.tex"] = table(
        "Area under the ROC curve by text-length quintile, shortest to longest, "
        "averaged over genres.",
        "tab:length",
        ["Detector"] + [f"Q{b}" for b in sorted(pivot.columns)], rows,
    )

    # Twelve languages clear the floor; six fit a column. Chosen by positive count so
    # the table shows the stack the corpus actually contains, and the rest stay in the
    # replication package rather than being averaged into something uninterpretable.
    lang_path = VALIDITY / "rq2_language.parquet"
    if lang_path.exists():
        language = pd.read_parquet(lang_path)
        top = (language.groupby("ext").n_pos.max().sort_values(ascending=False)
               .head(6).index.tolist())
        lpivot = language.pivot_table(index="detector", columns="ext", values="auroc")
        rows = [
            f"{LABELS[k]} & " + " & ".join(fmt(lpivot.loc[k].get(e, np.nan)) for e in top)
            + r" \\"
            for k in ALL if k in lpivot.index
        ]
        written["t_language.tex"] = table(
            "Area under the ROC curve by file type, on diffs. Negatives were matched to "
            "the positives on file type at sampling, so a difference here is the "
            "detector's.",
            "tab:language", ["Detector"] + [f"\\texttt{{.{e}}}" for e in top], rows,
            note=f"{len(language.ext.unique())} file types clear the floor of 100 "
                 "positives; the six most frequent are shown.",
        )

    apivot = agents.pivot_table(index="detector", columns="agent", values="auroc")
    agent_cols = list(apivot.columns)
    rows = [
        f"{LABELS[k]} & " + " & ".join(fmt(apivot.loc[k].get(a, np.nan)) for a in agent_cols)
        + r" \\"
        for k in ALL if k in apivot.index
    ]
    written["t_agents.tex"] = table(
        "Area under the ROC curve by agent, averaged over genres. The corpus allocates "
        "the positive set equally across agents.",
        "tab:agents",
        ["Detector"] + [a.replace("_", " ") for a in agent_cols], rows,
    )

    # N2 covers pull request bodies only, so this is a single-genre table by necessity.
    n2 = metrics[(metrics.genre == "pr_body") & metrics.auroc_n2.notna()]
    rows = []
    for key in ALL:
        cell = n2[n2.detector == key]
        if cell.empty:
            continue
        r = cell.iloc[0]
        shift = r.auroc_n2 - r.auroc_n1
        rows.append(
            f"{LABELS[key]} & {fmt(r.auroc_n1)} & {fmt(r.auroc_n2)} & {shift:+.3f} \\\\"
        )
    written["t_temporal.tex"] = table(
        "Pull request bodies scored against two negative sets: text from the same "
        "repositories written before ChatGPT, and human-written pull requests from the "
        "agent era.",
        "tab:temporal",
        ["Detector", "vs.\\ pre-ChatGPT", "vs.\\ contemporaneous", "Shift"], rows,
        align="lrrr",
        note="The supervised ceiling is absent: it is fit against the matched pre-ChatGPT "
             "negatives and never scores the contemporaneous set.",
    )

    # --- RQ3 -------------------------------------------------------------------
    written["t_youden.tex"] = table(
        "Youden's $J = s + c - 1$, the denominator of the Rogan--Gladen correction. "
        "The correction divides by this number.",
        "tab:youden", genre_header,
        by_genre(correction, ALL, "youden_j", lambda v: fmt(v, 3)),
        note="A value at or below zero leaves the correction undefined rather than "
             "imprecise.",
    )

    grid = [0.05, 0.10, 0.20, 0.30, 0.40]
    rows = []
    for ap in grid:
        counts = correction[f"ap{int(ap * 100):02d}_status"].value_counts()
        # The per-cent sign must be escaped: unescaped it opens a LaTeX comment and
        # silently swallows the rest of the row, including its line break.
        rows.append(
            f"{ap * 100:.0f}\\% & {int(counts.get('estimable', 0))} & "
            f"{int(counts.get('out of range', 0))} & {int(counts.get('undefined', 0))} \\\\"
        )
    written["t_estimable.tex"] = table(
        f"What the correction returns across all {len(correction)} detector and genre "
        "combinations, as a function of the share of artifacts a study reports flagging.",
        "tab:estimable",
        ["Reported share", "Estimable", "Out of range", "Undefined"], rows,
        align="lrrr",
        note="Out of range means the reported share implies a prevalence above one: no "
             "prevalence could produce that many flags through that instrument.",
    )

    rows = []
    for key in ALL:
        sub = correction[correction.detector == key]
        for genre, glabel in GENRES:
            cell = sub[sub.genre == genre]
            if cell.empty or cell.iloc[0]["ap20_status"] != "estimable":
                continue
            r = cell.iloc[0]
            rows.append(
                f"{LABELS[key]} & {glabel} & {pct(r['ap20_point'])} "
                f"({pct(r['ap20_lo'])}--{pct(r['ap20_hi'])}) \\\\"
            )
    written["t_corrected.tex"] = table(
        "Every detector and genre for which a study reporting 20\\% flagged artifacts "
        "could be corrected at all, with the corrected prevalence (\\%).",
        "tab:corrected", ["Detector", "Genre", "Corrected prevalence"], rows or
        [r"\multicolumn{3}{@{}l}{None.} \\"], align="llr",
    )

    written["validity_numbers.tex"] = macros(metrics, automation, correction, length)

    OUT.mkdir(parents=True, exist_ok=True)
    for name, content in written.items():
        (OUT / name).write_text(content)
    print(f"wrote {len(written)} files to {OUT}")

    missing = sorted(set(ALL) - set(metrics.detector.unique()))
    if missing:
        print(f"not yet scored, omitted from the tables: {', '.join(missing)}")
    return 0


def macros(metrics: pd.DataFrame, automation: pd.DataFrame,
           correction: pd.DataFrame, length: pd.DataFrame) -> str:
    def macro(name: str, value: str) -> str:
        return rf"\newcommand{{\{name}}}{{{value}}}"

    zero_shot = metrics[metrics.detector.isin(ZERO_SHOT)]
    ceiling = metrics[metrics.detector == "fingerprint"]
    judge = automation[automation.detector == "llm_judge"]
    sa = metrics[metrics.detector == "selfadmission"]
    status = correction["ap05_status"].value_counts()

    lines = [
        "% generated by analysis/03_validity/tables.py -- do not edit",
        macro("ZeroShotAurocMax", fmt(zero_shot.auroc_n1.max())),
        macro("ZeroShotAurocMin", fmt(zero_shot.auroc_n1.min())),
        macro("ZeroShotBelowChance", str(int((zero_shot.auroc_n1 < 0.5).sum()))),
        macro("ZeroShotCells", str(len(zero_shot))),
        macro("CeilingAurocMax", fmt(ceiling.auroc_n1.max())),
        macro("CeilingAurocMin", fmt(ceiling.auroc_n1.min())),
        macro("CeilingRecallMax", pct(ceiling.recall_at_fpr.max())),
        macro("JudgeBotFprMax", pct(judge.fpr_bots.max())),
        macro("JudgeBotFprMin", pct(judge.fpr_bots.min())),
        macro("JudgeBotRatioMin", fmt(judge.ratio.min(), 0)),
        macro("JudgeBotRatioMax", fmt(judge.ratio.max(), 0)),
        macro("SelfAdmissionRecallMax", pct(sa.recall_at_fpr.max())),
        macro("SelfAdmissionFprMax", pct(sa.fpr_achieved.max())),
        macro("CorrectionCells", str(len(correction))),
        macro("CorrectionUndefined", str(int(status.get("undefined", 0)))),
        macro("CorrectionOutOfRange", str(int(status.get("out of range", 0)))),
        macro("CorrectionEstimable", str(int(status.get("estimable", 0)))),
    ]
    for key, prefix in [("fast_detect_gpt", "FastDetect"), ("fingerprint", "Ceiling")]:
        sub = length[length.detector == key]
        if len(sub):
            lines += [
                macro(f"{prefix}ShortAuroc", fmt(sub[sub.bin == sub.bin.min()].auroc.mean())),
                macro(f"{prefix}LongAuroc", fmt(sub[sub.bin == sub.bin.max()].auroc.mean())),
            ]
    # Figures from the published operating points, quoted in the abstract and intro.
    published = VALIDITY / "rq1_published_points.parquet"
    if published.exists():
        pub = pd.read_parquet(published)
        bino = pub[pub.detector == "binoculars"]
        fast = pub[pub.detector == "fast_detect_gpt"]
        if len(bino):
            diff = bino[bino.genre == "diff"]
            lines += [
                macro("PublishedBinoDiffFpr", pct(diff.fpr_prellm.iloc[0]) if len(diff) else "---"),
                macro("PublishedBinoMinFpr", pct(bino.fpr_prellm.min())),
                macro("PublishedBinoMaxFpr", pct(bino.fpr_prellm.max())),
            ]
        if len(fast):
            lines += [
                macro("PublishedFastMinFpr", pct(fast.fpr_prellm.min())),
                macro("PublishedFastMaxFpr", pct(fast.fpr_prellm.max())),
            ]

    ceil_pr = correction[(correction.detector == "fingerprint") & (correction.genre == "pr_body")]
    if len(ceil_pr) and ceil_pr.iloc[0]["ap20_status"] == "estimable":
        r = ceil_pr.iloc[0]
        lines += [
            macro("CeilingCorrectedTwenty", pct(r["ap20_point"])),
            macro("CeilingCorrectedTwentyLo", pct(r["ap20_lo"])),
            macro("CeilingCorrectedTwentyHi", pct(r["ap20_hi"])),
        ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.exit(main())
