"""Language model prompted to judge authorship.

Several published estimates use a model as the classifier rather than a statistical
detector, so the approach has to be evaluated on the same corpus as the rest. This
adapter talks to the OpenAI-compatible API served by Ollama on the H100 host, either
through the OpenWebUI proxy or directly on the FH network.

Three properties are needed for the score to be usable:

Determinism. Temperature is zero and a seed is sent. A judge that returns different
answers on the same input cannot support a stable operating point.

A graded score, not a verdict. The model is asked for 0-100 rather than yes/no, because
an AUROC needs a ranking. A binary answer collapses the curve to one point and hides
exactly the calibration behaviour we are measuring.

A pinned model. The version string records the model actually served. A judge whose
weights change between runs produces numbers that cannot be reproduced, which is the
failure this paper is about.

Responses are cached on disk by (model, prompt revision, text hash). Scoring the full
corpus is tens of thousands of calls; a re-run after a crash should not repeat them.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _env import get, require  # noqa: E402
from _registry import register  # noqa: E402

CACHE_DIR = Path(__file__).resolve().parents[2] / "data" / "processed" / "llm_judge_cache"

# Bump when the prompt changes: cached answers from an older prompt are not comparable.
PROMPT_REVISION = "p1"

# Kept deliberately plain. Naming the agents or describing their style would tell the
# model what to look for and measure our prompt engineering rather than its judgement.
SYSTEM_PROMPT = (
    "You judge whether text from a software repository was written by a human "
    "developer or generated by an AI coding assistant. Answer with a single integer "
    "from 0 to 100: 0 means certainly human, 100 means certainly AI-generated. "
    "Reply with the number only."
)

USER_TEMPLATE = "Artifact type: {genre}\n\n---\n{text}\n---\n\nScore (0-100):"

NUMBER = re.compile(r"\d{1,3}")

# Long inputs cost time and most artifacts are short; truncation is reported rather
# than silently applied.
MAX_CHARS = 6000


class LLMJudge:
    name = "llm_judge"

    def __init__(self, model: str | None = None, workers: int = 8) -> None:
        from openai import OpenAI

        base = require("OLLAMA_URL").rstrip("/")
        self.model = model or get("OLLAMA_MODEL") or "llama3.1:8b"
        self.workers = workers
        # The scripts in this project append /v1 to reach the OpenAI-compatible route.
        self.client = OpenAI(
            base_url=f"{base}/v1",
            api_key=get("OLLAMA_API_KEY") or "unused",  # direct host access needs none
            timeout=120,
            max_retries=3,
        )
        self.version = f"llm_judge/{self.model}/{PROMPT_REVISION}"
        self.truncated = 0
        CACHE_DIR.mkdir(parents=True, exist_ok=True)

    def _cache_path(self, text: str) -> Path:
        digest = hashlib.sha256(
            f"{self.model}\x00{PROMPT_REVISION}\x00{text}".encode()
        ).hexdigest()
        return CACHE_DIR / digest[:2] / f"{digest}.json"

    def _ask(self, text: str, genre: str = "unknown") -> float:
        cache = self._cache_path(text)
        if cache.exists():
            try:
                return float(json.loads(cache.read_text())["score"])
            except (json.JSONDecodeError, KeyError, ValueError):
                pass  # corrupt entry: fall through and re-ask

        body = text[:MAX_CHARS]
        if len(text) > MAX_CHARS:
            self.truncated += 1

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": USER_TEMPLATE.format(genre=genre, text=body)},
                ],
                temperature=0,
                seed=7,
                max_tokens=8,
            )
            raw = (response.choices[0].message.content or "").strip()
        except Exception as exc:  # noqa: BLE001 - a failed call must not stop the sweep
            return float("nan")

        match = NUMBER.search(raw)
        if not match:
            return float("nan")
        score = min(100.0, float(match.group())) / 100.0

        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(json.dumps({"score": score, "raw": raw[:40]}))
        return score

    def score(self, texts: list[str]) -> list[float]:
        with ThreadPoolExecutor(max_workers=self.workers) as pool:
            return list(pool.map(self._ask, texts))


@register("llm_judge", kind="llm", needs_gpu=False,
          note="OpenAI-compatible endpoint on the H100 host; needs OLLAMA_URL")
def _build() -> LLMJudge:
    return LLMJudge()


def _check() -> int:
    """Verify the endpoint, list the models it serves, and score two known texts."""
    base = require("OLLAMA_URL")
    print(f"endpoint: {base}")
    print(f"api key : {'set' if get('OLLAMA_API_KEY') else 'not set (direct host access)'}")

    judge = LLMJudge()
    try:
        models = sorted(m.id for m in judge.client.models.list().data)
    except Exception as exc:  # noqa: BLE001
        print(f"\ncannot reach the endpoint: {str(exc)[:200]}")
        print("On the direct URL you need the FH network or VPN.")
        return 1

    print(f"\n{len(models)} model(s) served:")
    for m in models[:25]:
        print(f"  {m}{'  <- OLLAMA_MODEL' if m == judge.model else ''}")
    if judge.model not in models:
        print(f"\nOLLAMA_MODEL is {judge.model!r}, which this host does not serve.")
        print("Set OLLAMA_MODEL in .env to one of the above and pin it in the paper.")
        return 1

    print(f"\nsmoke test with {judge.model}:")
    samples = [
        ("fix typo in readme", "commit_message"),
        ("## Summary\n\nThis PR refactors the authentication module to improve "
         "maintainability.\n\n- Extracted helper functions\n- Added unit tests\n"
         "- Updated documentation\n\nLet me know if you have any questions!", "pr_body"),
    ]
    for text, genre in samples:
        score = judge._ask(text, genre)
        print(f"  {score:.2f}  {text.splitlines()[0][:55]!r}")
    print("\nHigher should mean more AI-like; check the second scores above the first.")
    return 0


if __name__ == "__main__":
    sys.exit(_check())
