"""Self-admission keyword search, as used by the prevalence studies.

Two of the four measurement studies this paper audits identify AI-written artifacts by
searching text for a developer's own admission that a tool wrote it, rather than by any
property of the writing. Mao et al. (arXiv:2603.27130) search code comments for a tool
name preceded by one of six prefix words, then filter the matches; Al Mujahid et al.
(arXiv:2606.06843) collect comments that explicitly reference an AI tool and classify
them afterwards. Reimplementing the mechanism puts that family on the same footing as
the statistical detectors.

Mao et al. give the construction of their list -- six prefixes crossed with eleven tool
names, sixty-six keywords in total -- but state that the list itself is omitted from
the paper and will be released with their script. What is reproduced here is therefore
the documented construction, not a copy of their file, and the two may differ in
spelling variants. The construction is the part that determines behaviour.

Their pipeline has three filtering stages after the keyword search: whole-word matching
to remove substring hits such as `use` inside another word, an attribution check that
the surrounding context describes code generation, and removal of mentions where the
tool is used for something other than writing code. The first is a property of the
patterns and is implemented. The second and third are LLM-assisted judgements in their
pipeline, and the harness already carries an LLM judge, so they are not duplicated
here; the effect of leaving them out is to make this adapter the upper bound of the
keyword stage, which is the quantity a prevalence estimate built on it inherits.

The published decision rule is a threshold of one: any hit marks the artifact as
AI-written. The score is therefore binary, and its AUROC is balanced accuracy rather
than a ranking quality. That is a property of the instrument, not of the evaluation.
"""

from __future__ import annotations

import re

from _registry import register

VERSION = "selfadmission/mao-almujahid/2026-08-13"

# The six prefix words of Mao et al., who take them from the earlier tool-mention work
# they extend.
PREFIXES = ["by", "with", "use", "used", "using", "from"]

# Their eleven tools: the four of the prior study, extended with seven more.
TOOLS = [
    "chatgpt",
    "copilot",
    "tabnine",
    "codewhisperer",
    "llama",
    "claude",
    "gemini",
    "deepseek",
    "grok",
    "qwen",
    "cursor ai",
]

# Prefix crossed with tool, whole-word on both sides. `\s+` rather than a single space
# so that a line break between the two still matches, which is common in wrapped
# comments and commit bodies.
KEYWORD = re.compile(
    r"\b(?:" + "|".join(PREFIXES) + r")\s+(?:" + "|".join(re.escape(t) for t in TOOLS) + r")\b",
    re.IGNORECASE,
)

# The explicit attribution patterns named in their semantic filtering stage. These fire
# without a tool name and are reported separately, since a bare "generated by" is much
# weaker evidence than one naming a model.
ATTRIBUTION = re.compile(r"\b(?:generated|written|enhanced|created)\s+by\b", re.IGNORECASE)


class SelfAdmissionDetector:
    name = "selfadmission"
    version = VERSION

    def score(self, texts: list[str]) -> list[float]:
        return [1.0 if KEYWORD.search(t or "") else 0.0 for t in texts]

    def explain(self, texts: list[str]) -> list[dict[str, bool]]:
        return [
            {
                "tool_mention": bool(KEYWORD.search(t or "")),
                "attribution_phrase": bool(ATTRIBUTION.search(t or "")),
            }
            for t in texts
        ]


@register("selfadmission", kind="keyword", needs_gpu=False,
          note="tool-name mentions after Mao et al. and Al Mujahid et al.; binary by design")
def _build() -> SelfAdmissionDetector:
    return SelfAdmissionDetector()
