#!/usr/bin/env python3
"""Emit the corpus composition table.

The frozen corpus is the methodological core of the paper, and readers need to see its
shape before any result: which sets exist, which genres each covers, and where a cell is
empty by design rather than by accident.

Writes paper/generated/t_corpus.tex.

Usage:
    python corpus_table.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "data" / "processed" / "corpus_v1" / "corpus.parquet"
OUT = ROOT / "paper" / "generated" / "t_corpus.tex"

SETS = [
    ("P", "Agent-attributed (P)"),
    ("N1", "Pre-ChatGPT, same repos (N1)"),
    ("N2", "Contemporaneous humans (N2)"),
    ("N3", "Pre-ChatGPT automation (N3)"),
]
GENRES = [
    ("commit_message", "Commit msg"),
    ("pr_body", "PR body"),
    ("issue_body", "Issue"),
    ("comment", "Comment"),
    ("diff", "Diff"),
]


def main() -> int:
    if not CORPUS.exists():
        raise SystemExit(f"missing {CORPUS}")
    corpus = pd.read_parquet(CORPUS, columns=["set", "genre"])
    counts = corpus.groupby(["set", "genre"]).size().unstack(fill_value=0)

    rows = []
    for key, label in SETS:
        if key not in counts.index:
            continue
        cells = [f"{counts.loc[key].get(g, 0):,}" if counts.loc[key].get(g, 0) else "---"
                 for g, _ in GENRES]
        total = int(counts.loc[key].sum())
        rows.append(f"{label} & " + " & ".join(cells) + f" & {total:,} \\\\")
    grand = int(counts.to_numpy().sum())
    header = ["Set"] + [lbl for _, lbl in GENRES] + ["Total"]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rf"""% generated by analysis/01_corpus/corpus_table.py -- do not edit
\begin{{table}}[t]
\caption{{The frozen corpus, {grand:,} texts. Every detector scores every cell, and every
detection in N1 or N3 is an error by construction.}}
\label{{tab:corpus}}
\small
\begin{{tabular}}{{@{{}}l{"r" * (len(header) - 1)}@{{}}}}
\toprule
{" & ".join(header)} \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}

\vspace{{2pt}}
{{\footnotesize Empty cells are empty by design: AIDev supplies contemporaneous human
pull requests only, and repository automation writes no code diffs.}}
\end{{table}}
""")
    print(f"wrote {OUT} ({grand:,} texts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
