#!/usr/bin/env python3
"""Assemble and freeze corpus v1 from the collected parts.

Combines the sampled positives with the three negative sets, matches negatives to the
positive length distribution within genre, and writes the frozen corpus with a manifest
recording seeds, counts and the matching that was applied.

Length matching matters more than it may look. Detector scores depend on input length,
and the sets differ: pre-LLM commit messages run shorter than agent-authored ones. An
unmatched comparison would partly measure length rather than authorship. We therefore
write both a matched and an unmatched corpus; the difference between results on the two
estimates how much of any separation is length.

Negative sets:
    N1  pre-LLM, same repositories, human-authored
    N2  contemporaneous human pull requests from AIDev
    N3  pre-LLM automation accounts

Usage:
    python freeze_corpus.py
    python freeze_corpus.py --per-genre 5000 --seed 7

Output: data/processed/corpus_v1/corpus.parquet and corpus_manifest.json
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

from _text import is_bot_author

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw" / "aidev"
CORPUS = ROOT / "data" / "processed" / "corpus_v1"

DECILES = 10
COLUMNS = ["source_id", "set", "genre", "agent", "repo", "text", "n_chars", "label", "ext"]


def load_positives() -> pd.DataFrame:
    df = pd.read_parquet(CORPUS / "positives.parquet")
    df["set"] = "P"
    df["label"] = 1
    df["ext"] = (
        df.filename.dropna().str.rsplit(".", n=1).str[-1].str.lower()
        if "filename" in df
        else None
    )
    return df


def load_n1_commits() -> pd.DataFrame:
    df = pd.read_parquet(
        CORPUS / "n1_commits.parquet",
        columns=["repo", "sha", "text", "n_chars", "is_bot", "is_merge", "genre"],
    )
    df = df[~df.is_merge]  # merge messages are generated by git, not written
    df["set"] = df.is_bot.map({True: "N3", False: "N1"})
    df["source_id"] = df.sha
    df["agent"] = None
    df["label"] = 0
    return df


def load_n1_api() -> pd.DataFrame:
    path = CORPUS / "n1_api.parquet"
    if not path.exists():
        print(f"note: {path.name} not present, skipping issue/PR/comment negatives")
        return pd.DataFrame(columns=COLUMNS)
    df = pd.read_parquet(path)
    df["set"] = df.is_bot.map({True: "N3", False: "N1"})
    df["source_id"] = df.id.astype(str)
    df["agent"] = None
    df["label"] = 0
    return df


def load_n1_diffs() -> pd.DataFrame:
    path = CORPUS / "n1_diffs.parquet"
    if not path.exists():
        print(f"note: {path.name} not present, skipping diff negatives")
        return pd.DataFrame(columns=COLUMNS)
    df = pd.read_parquet(path)
    df["set"] = "N1"
    df["agent"] = None
    df["label"] = 0
    return df


def load_n2() -> pd.DataFrame:
    """Contemporaneous human pull requests: same period as the positives."""
    df = pd.read_parquet(
        RAW / "human_pull_request.parquet", columns=["id", "body", "user", "repo_url"]
    )
    df = df[df.body.notna()]
    df["text"] = df.body.str.strip()
    df = df[df.text.str.len() > 10]
    # AIDev labels these Human, but the accounts are not screened for automation.
    df = df[~df.user.map(is_bot_author)]
    return pd.DataFrame(
        {
            "source_id": df.id.astype(str),
            "set": "N2",
            "genre": "pr_body",
            "agent": None,
            "repo": df.repo_url.str.replace("https://github.com/", "", regex=False),
            "text": df.text,
            "n_chars": df.text.str.len(),
            "label": 0,
        }
    )


def match_lengths(
    positives: pd.DataFrame, negatives: pd.DataFrame, seed: int
) -> tuple[pd.DataFrame, list]:
    """Sample negatives to follow the positive distribution within each genre.

    Deciles are taken from the positive side and negatives drawn to the same shape.
    Where a bin is short the deficit is reported rather than backfilled from
    neighbouring bins, which would reintroduce the imbalance being corrected.

    For diffs the match is on file extension as well as length. The collected sets
    differ sharply by language: pre-LLM history in these repositories is heavier in
    HTML and C++ while agent contributions are heavier in TypeScript. Matching on
    length alone would leave a detector able to separate the classes by language.
    """
    kept, report = [], []
    for genre, pos in positives.groupby("genre"):
        neg = negatives[negatives.genre == genre]
        if neg.empty:
            report.append({"genre": genre, "wanted": int(len(pos)), "got": 0,
                           "note": "no negatives available"})
            continue

        # Diffs match within language; other genres have no language to match on.
        strata = [(None, pos, neg)]
        if genre == "diff":
            strata = [
                (ext, grp, neg[neg.ext == ext])
                for ext, grp in pos.groupby(pos.ext.fillna("none"))
            ]

        for stratum, pos_s, neg_s in strata:
            if pos_s.empty:
                continue
            if neg_s.empty:
                report.append({"genre": genre, "stratum": stratum,
                               "wanted": int(len(pos_s)), "got": 0,
                               "note": "no negatives in this language"})
                continue
            edges = pos_s.n_chars.quantile([i / DECILES for i in range(DECILES + 1)]).values
            edges[0], edges[-1] = -1, float("inf")
            pos_bins = pd.cut(pos_s.n_chars, bins=edges, duplicates="drop")
            neg_bins = pd.cut(neg_s.n_chars, bins=edges, duplicates="drop")
            for interval, want in pos_bins.value_counts().items():
                pool = neg_s[neg_bins == interval]
                take = min(int(want), len(pool))
                if take:
                    kept.append(pool.sample(take, random_state=seed))
                if take < want:
                    report.append({"genre": genre, "stratum": stratum,
                                   "bin": str(interval), "wanted": int(want), "got": take})

    matched = pd.concat(kept, ignore_index=True) if kept else pd.DataFrame(columns=COLUMNS)
    return matched, report


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--per-genre", type=int, default=5000, help="negative cap per genre")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    pos = load_positives()
    negatives = pd.concat(
        [load_n1_commits(), load_n1_api(), load_n1_diffs(), load_n2()], ignore_index=True
    )
    for frame in (pos, negatives):
        for col in COLUMNS:
            if col not in frame:
                frame[col] = None
    pos, negatives = pos[COLUMNS], negatives[COLUMNS]

    print(f"\npositives: {len(pos):,}")
    print(pos.groupby("genre").size().to_string())
    print(f"\nnegatives available: {len(negatives):,}")
    print(negatives.groupby(["set", "genre"]).size().to_string())

    # N1 carries the counterfactual false positive rate, so it is capped per genre at
    # the precision target rather than at whatever happens to have been collected.
    capped = []
    for (nset, genre), grp in negatives.groupby(["set", "genre"]):
        take = min(args.per_genre, len(grp))
        capped.append(grp.sample(take, random_state=args.seed) if take < len(grp) else grp)
    negatives = pd.concat(capped, ignore_index=True)

    matched, deficits = match_lengths(pos, negatives[negatives.set == "N1"], args.seed)
    matched["matched"] = True
    unmatched = negatives.copy()
    unmatched["matched"] = False
    pos = pos.copy()
    pos["matched"] = None

    corpus = pd.concat([pos, unmatched, matched], ignore_index=True)
    corpus["corpus_version"] = "v1"

    CORPUS.mkdir(parents=True, exist_ok=True)
    out = CORPUS / "corpus.parquet"
    corpus.to_parquet(out, index=False)

    manifest = {
        "generated": datetime.now(UTC).isoformat(),
        "version": "v1",
        "seed": args.seed,
        "per_genre_cap": args.per_genre,
        "length_deciles": DECILES,
        "counts": {
            "positives": int(len(pos)),
            "negatives_unmatched": int(len(unmatched)),
            "negatives_matched": int(len(matched)),
        },
        "by_set_genre": {
            f"{s}/{g}": int(n)
            for (s, g), n in corpus.groupby(["set", "genre"]).size().items()
        },
        "matching_deficits": deficits,
    }
    (CORPUS / "corpus_manifest.json").write_text(json.dumps(manifest, indent=2, default=str))

    print(f"\nfrozen corpus: {len(corpus):,} rows")
    print(corpus.groupby(["set", "genre"]).size().to_string())
    if deficits:
        print(f"\n{len(deficits)} length bins under-filled (see manifest)")
    print(f"\nwrote {out}\n      {CORPUS / 'corpus_manifest.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
